version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pass_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: pass_system_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pass_network

  redis:
    image: redis:7-alpine
    container_name: pass_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pass_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pass_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: postgresql://admin:secretpassword@postgres:5432/pass_system_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - pass_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pass_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://192.168.3.17:5000/api
    depends_on:
      - backend
    networks:
      - pass_network

volumes:
  postgres_data:
  redis_data:

networks:
  pass_network:
    driver: bridge